language: minimal

sudo: required

service: docker

env:
  - DOCKER_COMPOSE_VERSION=1.26.0

# Pre-testing installs
install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - aws eks --region ${AWS_REGION} update-kubeconfig --name ${AWS_EKS_CLUSTER}

# Scripts to be run such as tests
# before_script:
#   - echo "no tests"

script:
  - docker-compose -f udagram-deployment/docker/docker-compose-build.yaml build --parallel
  - docker-compose -f udagram-deployment/docker/docker-compose-build.yaml push
  - kubectl apply -f udagram-deployment/k8s/aws-secret.yaml
  - kubectl apply -f udagram-deployment/k8s/env-secret.yaml
  - kubectl apply -f udagram-deployment/k8s/backend-feed-deployment.yaml
  - kubectl apply -f udagram-deployment/k8s/backend-user-deployment.yaml
  - kubectl apply -f udagram-deployment/k8s/reverseproxy-deployment.yaml
  - kubectl apply -f udagram-deployment/k8s/frontend-deployment.yaml
  - kubectl apply -f udagram-deployment/k8s/backend-feed-service.yaml
  - kubectl apply -f udagram-deployment/k8s/backend-user-service.yaml
  - kubectl apply -f udagram-deployment/k8s/reverseproxy-service.yaml
  - kubectl apply -f udagram-deployment/k8s/frontend-service.yaml

after_success:
  - "travis_wait 30 sleep 2 &"
  - kubectl get pods
  - kubectl get svc